// Content for every section: copy, colours, wallpapers, method notes and sources.
// code, kind and record fill the front page's departure board; scene is the chapter's
// particle scene there (public/particles/<file>_{d,p}.bin) and still its no-WebGL fallback
// (public/wallpapers/feature/<still>_{d,p}.webp).
// Wallpaper files live in public/wallpapers/{preview,full}/<file>_{desktop,phone}.{webp,png}

export const SECTIONS = [
  {
    id: 'fuji',
    code: 'FJ',
    kind: { jp: '大地', en: 'Earth' },
    record: '3,776 m',
    scene: { file: 'fuji3d', threeD: true, title: 'Mount Fuji and other summits', line: 'Fuji built from light: every point sits at its real place on the mountain, from 1,000 m up to the 3,776 m summit, slowly turning.' },
    still: 'fuji_ridges',
    short: 'Fuji',
    kanji: '富士山',
    kana: 'ふじさん',
    title: 'Mount Fuji and other summits',
    accent: '#ff8a4c',
    anim: 'fuji',
    lede:
      'Mount Fuji as glowing contour lines, one every 10 metres, coloured like the red Fuji of a summer sunrise: indigo at the foot, crimson on the slopes, white at the 3,776 m summit. The notch on the south-east flank is the Hōei crater of 1707, the last eruption. Beside it stand the next two highest summits, Kita-dake in the Southern Alps and Oku-hotaka-dake in the Northern Alps, seen from the east.',
    facts: [
      ['3,776 m', 'summit'],
      ['10 m', 'between contours'],
      ['30 m', 'elevation grid'],
    ],
    scale: { label: 'Elevation', from: '0 m', to: '3,776 m', stops: ['#291a73', '#731a8c', '#d91f4d', '#ff6b2e', '#ffcc8c', '#ffffff'] },
    wallpapers: [
      { file: 'fuji', jp: '富士山', en: 'Mount Fuji', note: 'Contours bunch together where the cone is steepest. The flat ring at the base is the old lava plain that surrounds the mountain.' },
      { file: 'fuji_ridges', jp: '稜線の富士', en: 'The summit cone in ridge lines', note: 'Profiles of the cone about 150 m apart, seen from the south at true vertical scale, each hiding the ones behind it. Close enough to read the crater rim, and Hōei, the peak on the rim of the 1707 crater.' },
      { file: 'fuji_points', jp: '光の富士', en: 'Fuji in light', note: 'The 3D view from the front page as a wallpaper: 640,000 points along every 10 m contour from 1,000 m to the summit, each at its real position and true vertical scale, seen in perspective; points behind the near slope are left out. The lower slopes dissolve into the dark; the crater notch sits on top.' },
      { file: 'kitadake_side', jp: '北岳', en: 'Kita-dake from the east', note: 'The second-highest summit in Japan, 3,193 m, in the Southern Alps, with Aino-dake (3,190 m) beside it to the south. The range as layered skylines about 450 m apart, seen from 30 km east.' },
      { file: 'kitadake_ridges', jp: '北岳の稜線', en: 'Kita-dake in ridge lines', note: 'Close up from the east, from the foot of its east face: profiles about 150 m apart, brightest near the summit so the peak stands out from the range.' },
      { file: 'hotaka_side', jp: '奥穂高岳', en: 'Oku-hotaka-dake from the east', note: 'The highest summit of the Northern Alps, 3,190 m, with the spire of Yari-ga-take (3,180 m) 6 km to the north: the Yari-Hotaka skyline as layered profiles seen from 30 km east.' },
      { file: 'hotaka_ridges', jp: '奥穂高岳の稜線', en: 'Oku-hotaka-dake in ridge lines', note: 'Close up from the east, rising from the Karasawa cirque below the summit: profiles about 150 m apart, brightest near the summit.' },
    ],
    method: [
      ['Data', 'A 1 arc-second (about 30 m) elevation model of the Fuji area.'],
      ['Lines', 'Contours traced every 10 m with marching squares; every 100 m slightly brighter. Low hills are dimmed so the cone stays the subject.'],
      ['Ridge lines', 'Profiles across the line of sight are drawn near to far; a running horizon per pixel column keeps only what rises above the lines already drawn, so each line hides the ones behind it. In the close-ups of the Alps the light fades with distance from the summit.'],
      ['The Alps', 'Kita-dake and Oku-hotaka-dake come from the Copernicus DEM GLO-30, also 30 m. A grid that coarse rounds the sharpest summits off and even ranks Aino-dake above Kita-dake, so the labels give the official heights. On ground that steep, 10 m contour rings pile into solid bands, so their side views show the ranges as layered skylines instead.'],
    ],
    sources: [['geovista-data: Fuji DEM', 'https://github.com/bjlittle/geovista-data'],
      ['Copernicus DEM GLO-30, produced using Copernicus WorldDEM-30 © DLR e.V. 2010-2014 and © Airbus Defence and Space GmbH 2014-2018 provided under COPERNICUS by the European Union and ESA; all rights reserved', 'https://registry.opendata.aws/copernicus-dem/']],
  },
  {
    id: 'earthquakes',
    code: 'EQ',
    kind: { jp: '大地', en: 'Earth' },
    record: '30,167 quakes',
    scene: { file: 'japan', title: 'Every earthquake since 1973', line: '30,167 quakes of magnitude 4.5 and up. No coastline is drawn: the plates draw Japan by themselves.' },
    still: 'japan',
    short: 'Quakes',
    kanji: '地震',
    kana: 'じしん',
    title: 'Earthquakes',
    accent: '#ffcf8a',
    anim: 'quakes',
    lede:
      'Every earthquake of magnitude 4.5 or more recorded around Japan since 1973. Each point of light is one quake: size is magnitude, colour is depth. No coastline is drawn. The plates draw Japan by themselves.',
    facts: [
      ['30,167', 'earthquakes'],
      ['M9.1', 'largest, 11 March 2011'],
      ['683 km', 'deepest, Izu–Bonin slab'],
    ],
    scale: { label: 'Hypocentre depth', from: '0 km', to: '650 km', stops: ['#ffdb9e', '#ff7330', '#e6294d', '#8c33d9', '#4059ff'] },
    wallpapers: [
      { file: 'japan', jp: '日本', en: 'Japan', note: 'Four plates meet under Japan. The bright band is the Japan Trench; the violet branch hanging below is the Pacific plate sinking towards 680 km under the Izu–Bonin arc. The frame holds 27,900 of the 30,167 quakes; the rest lie in the faded tails.' },
      { file: 'quakes_3d', jp: '沈み込み', en: 'The plates in 3D', note: 'The 22,141 quakes east of 136°E lifted out of the map, each at its real depth, seen from above the Pacific. The bright arc is the trench; beneath it the Pacific plate hangs as a sheet of light, and under the Izu–Bonin arc it plunges almost straight down to 680 km. Depth is stretched twice so the slab can be seen.' },
      { file: 'tohoku', jp: '東北', en: 'Tōhoku', note: 'The densest glow offshore is the aftershock zone of the 2011 Great Tōhoku earthquake: more than 3,700 quakes of M4.5+ in the following twelve months.' },
      { file: 'tokyo', jp: '東京・関東', en: 'Tokyo & Kantō', note: 'Off the Bōsō Peninsula, three plates meet at one of the few trench-trench-trench triple junctions on Earth.' },
      { file: 'kurils', jp: '北海道・千島', en: 'Hokkaido & Kurils', note: 'The Kuril Trench runs from Hokkaido to Kamchatka. Red and violet flecks are quakes inside the slab, hundreds of kilometres down.' },
      { file: 'izu', jp: '伊豆・小笠原', en: 'Izu–Bonin Trench', note: 'Subduction in one picture: the amber line is the shallow arc, the violet line beside it is the same plate seen 600 km deeper.' },
      { file: 'ryukyu', jp: '琉球', en: 'Ryūkyū Arc', note: 'The Philippine Sea plate dives under the Ryūkyū islands. Behind the arc, the Okinawa Trough is slowly rifting open.' },
      { file: 'west', jp: '西日本', en: 'Western & Central Japan', note: 'Quieter inland, which makes its big events stand out: Kobe 1995, Kumamoto 2016 and Noto 2024.' },
      { file: 'tohoku_2011', jp: '東日本大震災', en: 'The week after the M9', note: 'Every quake of M2.5 and up that JMA located in the seven days after 14:46 on 11 March 2011: 7,138 of them, filling a zone 500 km long within hours. White marks the first hours, amber the days after; the brightest star is the M9.0 itself.' },
      { file: 'kumamoto_2016', jp: '熊本地震', en: 'Kumamoto 2016', note: 'An M6.5 on 14 April, then an M7.3 on the same fault 28 hours later. The 13,445 quakes of M1.5 and up to the end of 2016 trace the Futagawa and Hinagu faults, white where the first hours struck, then run north-east past Aso towards Ōita as later bursts cool to red.' },
    ],
    method: [
      ['Data', 'USGS earthquake catalogue (ComCat), magnitude 4.5 and up, 1973 to October 2026, box 121–150°E, 23–47°N. Nuclear tests and landslides are filtered out.'],
      ['Light', 'Each quake is a Gaussian glow added into a float buffer, never painted over, so dense trenches build up light on their own. Quakes of M7+ get four faint rings.'],
      ['Rotation', 'The national view is rotated along its main axis (found with PCA) so the arc fills the long side of the screen. A small arrow marks north.'],
      ['Sequences', 'The Tōhoku and Kumamoto pictures use the JMA earthquake catalogue, which records far smaller quakes than the USGS one. Colour there is time since the first big shock, on a log scale, from white to deep red.'],
      ['3D view', 'Each quake is placed at its longitude, latitude and depth in kilometres, depth stretched twice, and seen through a perspective camera from above the Pacific. West of 136°E the quakes fade out, so the view holds the Pacific plate alone.'],
    ],
    sources: [
      ['USGS ANSS Comprehensive Earthquake Catalog', 'https://earthquake.usgs.gov/fdsnws/event/1/'],
      ['JMA earthquake catalogue (震源データ)', 'https://www.data.jma.go.jp/eqev/data/bulletin/hypo.html'],
    ],
  },
  {
    id: 'volcanoes',
    code: 'VO',
    kind: { jp: '大地', en: 'Earth' },
    record: '1,492 eruptions',
    scene: { file: 'volcanoes_japan', title: 'Japan\'s volcanoes, from white-hot to cold', line: 'Colour is how long since each one last erupted, brightness how often it has. They line up above the sinking plates.' },
    still: 'volcanoes_japan',
    short: 'Volcanoes',
    kanji: '火山',
    kana: 'かざん',
    title: 'Volcanoes',
    accent: '#ff5640',
    anim: 'volcanoes',
    lede:
      'Every volcano in Japan active in the last 12,000 years, 116 of them, as embers: white-hot where one has erupted this century, cooling through orange to deep red where it has slept for millennia, brighter the more eruptions are on record. They stand in lines above the sinking plates: from the Northern Territories through Hokkaido and Tokyo to the Ogasawara Islands over the Pacific plate, and from western Honshu and Kyushu down the Ryukyus over the Philippine Sea plate.',
    facts: [
      ['116', 'volcanoes'],
      ['1,492', 'confirmed eruptions'],
      ['22', 'erupted since 2000'],
    ],
    scale: { label: 'Since the last eruption', from: 'this century', to: '10,000 years', stops: ['#fff7e6', '#ffdb8c', '#ff9e40', '#ff5c24', '#e0241f', '#8c0f1f'] },
    wallpapers: [
      { file: 'volcanoes_japan', jp: '日本の火山', en: 'Volcanoes of Japan', note: 'The 116 volcanoes of Japan on the Smithsonian list, the 11 of the Northern Territories among them, over land drawn faintly by its rivers. Aso, with 172 eruptions on record, burns brightest. The white points are the 22 that have erupted since 2000: Sakurajima, Aso and Ontake among them, Etorofu-Yakeyama on Iturup, and Nishinoshima and Fukutoku-Okanoba far out in the Ogasawaras.' },
      { file: 'volcanoes_slab', jp: '沈み込む板の上', en: 'Above the sinking plate', note: 'The same volcanoes over the earthquakes of the Earthquakes chapter, brightest where they are 90 to 160 km deep. Every line of volcanoes stands on the inner edge of that band. Under the volcanoes of northeast Japan and the Kurils the deep quakes sit at a median of 123 km: there the sinking plate gives up its water, and the hot rock above it melts.' },
      { file: 'volcanoes_stripes', jp: '噴火の縞', en: 'Eruption stripes', note: 'One thread per volcano, south at the bottom, from 1600 to today; each of the 825 confirmed eruptions lights its thread for as long as it lasted. The record grows dense after 1900, as observation spread, and some threads hardly go dark: Sakurajima has erupted almost without pause since 1955, Suwanosejima since 2004.' },
    ],
    method: [
      ['Data', 'Volcanoes of the World, from the Global Volcanism Program of the Smithsonian Institution: every Holocene volcano it lists for Japan (105) and for the Northern Territories, which it files as Japan administered by Russia (11), and the 1,769 eruptions recorded at these 116, 1,492 confirmed. JMA\'s own list of 111 active volcanoes, which also takes in the Northern Territories, counts some differently.'],
      ['Embers', 'Colour is the time since the last confirmed eruption on a log scale, white this century, deep red after 10,000 years; volcanoes with no dated eruption take the deepest red. Brightness grows with the number of confirmed eruptions.'],
      ['Plate', 'Earthquakes from the USGS catalogue, as in the Earthquakes chapter, weighted to glow brightest between 90 and 160 km deep. The 123 km figure is the median depth of the quakes deeper than 40 km within 30 km of the 59 land volcanoes of the Northeast Japan and Kuril arcs.'],
      ['Stripes', 'The 825 confirmed eruptions since 1600, at 68 volcanoes, each drawn from its start to its end (eruptions still going run to today), with a burst at its start. Colour and brightness follow the VEI, the 0 to 8 scale of explosivity. The Smithsonian files Sakurajima under the Aira caldera and Tarumae under Shikotsu; the labels use the names Japan knows.'],
      ['Animation', 'The same eruptions year by year: a ring of light at each start, a glow for as long as it lasts, then an ember cooling over about 25 years.'],
    ],
    sources: [
      ['Global Volcanism Program, Smithsonian Institution: Volcanoes of the World (accessed October 2026)', 'https://volcano.si.edu/'],
      ['USGS ANSS Comprehensive Earthquake Catalog', 'https://earthquake.usgs.gov/fdsnws/event/1/'],
    ],
  },
  {
    id: 'tsunami',
    code: 'TS',
    kind: { jp: '海', en: 'Sea' },
    record: '24 hours, 2011',
    scene: { file: 'tsunami', title: 'The 2011 tsunami crossing the Pacific', line: 'Undersea ridges bend the wave into beams aimed at Hawaii, Chile and New Zealand. Computed from the physics, not drawn.' },
    still: 'tsunami',
    short: 'Tsunami',
    kanji: '津波',
    kana: 'つなみ',
    title: 'Tsunami',
    accent: '#3ff2d0',
    anim: 'tsunami',
    lede:
      'The 2011 Tōhoku tsunami crossing the Pacific, simulated from the shallow-water equations on the real depth of the ocean. The bright beams are not drawn by hand: undersea ridges act like lenses and channel the energy towards Hawaii, Chile and New Zealand. Two pictures show what it did on Japan\'s own coast, from the marks the water left: how high it climbed, and how far inland it went.',
    facts: [
      ['24 h', 'of ocean simulated'],
      ['~700 km/h', 'wave speed over deep ocean'],
      ['1,051 × 745', 'grid cells, 10 arc-minutes'],
    ],
    scale: { label: 'Highest wave', from: '5 cm', to: '4 m', stops: ['#06123d', '#004d8c', '#00b3cc', '#8cf2ff', '#ffffff'] },
    wallpapers: [
      { file: 'tsunami', jp: '津波', en: 'Tōhoku tsunami, 2011', note: 'The highest wave reached at every point of the Pacific in the 24 hours after the earthquake. Faint rings mark each hour of travel time.' },
      { file: 'tsunami_heights', jp: '津波の高さ', en: 'How high it reached', note: 'Every mark the 2011 tsunami left on the coast that the joint survey measured and graded reliable: 5,476 points from Hokkaido to Kyushu. Colour is the height above the tide, up to 40.0 m at Ryōri, Ōfunato.' },
      { file: 'tsunami_inland', jp: '浸水', en: 'How far it came inland', note: 'The Sendai plain and Ishinomaki, from Sōma to the Oshika peninsula. Each mark sits where the water reached; colour is its distance from the shore, teal at the beach, white 5 km inland. On the Kitakami river a mark was measured 14.5 km from the shore.' },
    ],
    method: [
      ['Physics', 'Linear shallow-water equations on a sphere, solved on a staggered grid every 12.5 seconds of simulated time. Land is a wall; the open edges absorb the wave.'],
      ['Source', 'An idealised seafloor uplift along the Japan Trench: about +5 m on the trench side and −2 m landward, 400 by 150 km. Close to the real event, not the published rupture model, so heights are approximate.'],
      ['Ocean depth', 'ETOPO1 bathymetry resampled to 10 arc-minutes (about 18 km).'],
      ['Survey', 'The two coast pictures are measured, not simulated: the final release (29 December 2012) of the 2011 Tohoku Earthquake Tsunami Joint Survey Group, tide-corrected. Only marks graded A (clear trace) or B (reliable witness) are drawn: 5,476, of which 4,025 have a distance from the shore. Heights are above the tide at the time: a run-up height is the ground height where the water stopped, an inundation height the height of the water where it stood.'],
    ],
    sources: [
      ['ETOPO1 Global Relief Model (NOAA)', 'https://doi.org/10.7289/V5C8276M'],
      ['Earth topography grid, 10 arc-minutes (Fatiando a Terra)', 'https://github.com/fatiando-data/earth-topography-10arcmin'],
      ['2011 Tohoku Earthquake Tsunami Joint Survey Group, release 20121229', 'https://coastal.jp/ttjt/'],
      ['Mori, Takahashi et al. (2012), Nationwide survey of the 2011 Tohoku earthquake tsunami, Coastal Engineering Journal 54(1)', 'https://doi.org/10.1142/S0578563412500015'],
    ],
  },
  {
    id: 'typhoons',
    code: 'TY',
    kind: { jp: '空', en: 'Sky' },
    record: '1,951 storms',
    scene: { file: 'typhoons', title: 'Seventy-five years of typhoons', line: 'Born in the tropics, they drift west, then curve north toward Japan. The white arcs fell below 930 hPa.' },
    still: 'typhoons',
    short: 'Typhoons',
    kanji: '台風',
    kana: 'たいふう',
    title: 'Typhoons',
    accent: '#7fe8ff',
    anim: 'typhoons',
    lede:
      'Every typhoon tracked by the Japan Meteorological Agency from 1951 to 2025. Storms are born in the warm tropics, drift west, then curve north and east towards Japan. The violent ones, below 930 hPa at their peak, burn white.',
    facts: [
      ['1,951', 'storms'],
      ['349', 'below 930 hPa'],
      ['75', 'seasons'],
    ],
    scale: { label: 'Central pressure', from: '1006 hPa', to: '905 hPa', stops: ['#0d38f2', '#008cff', '#1ae6ff', '#b3ffff', '#ffffff'] },
    wallpapers: [
      { file: 'typhoons', jp: '台風', en: 'Northwest Pacific typhoons', note: 'Every storm is a faint line; those that reached 930 hPa or lower are drawn bright, whitest where they peaked. The fan opening north-east is the recurve that brings typhoons to Japan.' },
      { file: 'typhoon_decades', jp: '十年ごと', en: 'Decade by decade', note: 'The same map once for every decade since 1951. The count hardly moves: about 24 to 30 storms a season, four or five of them deepening below 930 hPa, in every full decade. The last panel holds only the six seasons from 2020 to 2025, with fewer violent storms so far (20).' },
      { file: 'isewan_1959', jp: '伊勢湾台風', en: 'Typhoon Vera, 1959', note: 'The deadliest typhoon of postwar Japan. Vera deepened to 895 hPa on 23 September, made landfall on the Kii Peninsula on the evening of the 26th and drove a storm surge into Ise Bay; more than 5,000 people died or went missing. Each bead is six hours of travel: they spread apart as the storm races north across Honshu.' },
      { file: 'hagibis_2019', jp: '令和元年東日本台風', en: 'Typhoon Hagibis, 2019', note: 'Hagibis deepened to 915 hPa on 7 October, then curved north and made landfall on the Izu Peninsula on the evening of the 12th, its rain bursting river banks across eastern Japan. Each bead is six hours: the slow, bright days over the ocean, then the long strides as it sped away past Tōhoku.' },
    ],
    method: [
      ['Data', 'JMA RSMC Tokyo best track: 6-hourly position, grade and central pressure of every storm since 1951.'],
      ['Colour', 'Lower pressure means a stronger storm: deep blue at birth, cyan as it deepens, white at its peak. Extratropical tails fade to violet.'],
    ],
    sources: [['JMA RSMC Tokyo best track data', 'https://www.jma.go.jp/jma/jma-eng/jma-center/rsmc-hp-pub-eg/besttrack.html']],
  },
  {
    id: 'rivers',
    code: 'RV',
    kind: { jp: '水', en: 'Water' },
    record: '127,393 km',
    scene: { file: 'rivers_japan', title: 'Every river in Japan', line: 'Each one as bright as the water it carries. No coastline is drawn: the rivers draw the islands by themselves.' },
    still: 'rivers_japan',
    short: 'Rivers',
    kanji: '川',
    kana: 'かわ',
    title: 'Rivers',
    accent: '#8fb4ff',
    anim: 'rivers',
    lede:
      'Every river in Japan, 127,393 km of them, each as bright as the water it carries. No coastline is drawn: thousands of mountain streams draw the islands by themselves, and the great rivers burn white, the Ishikari and the Shinano pouring nearly 500 cubic metres into the sea every second.',
    facts: [
      ['127,393 km', 'of river'],
      ['3,141', 'river systems'],
      ['15,908 km²', 'Tone basin, the largest'],
    ],
    scale: { label: 'Average flow', from: '0.1 m³/s', to: '400 m³/s', stops: ['#3842d9', '#4085ff', '#8cc7ff', '#dbf0ff', '#ffffff'] },
    wallpapers: [
      { file: 'rivers_japan', jp: '日本の川', en: 'Rivers of Japan', note: 'Not one line of coast, only rivers: 42,984 reaches, each lit by its average flow. The white veins are the great rivers; the blue lace between them is the mountain streams, so dense on these steep, rainy islands that the land draws itself.' },
      { file: 'rivers_basins', jp: '流域', en: 'River systems', note: 'The same rivers, each of the 3,141 river systems in its own colour, so the watersheds show where the rain decides which sea it will reach. The largest patches are the Tone in Kantō, the Ishikari in Hokkaido and the Shinano, from Nagano to Niigata.' },
      { file: 'rivers_kanto', jp: '関東', en: 'Kantō and the Tone', note: 'Japan\'s largest river basin, 15,908 km² in this data. The Tone gathers the rivers of Gunma and Tochigi and runs east to the Pacific at Chōshi. It once emptied into Tokyo Bay; engineers of the Edo period turned it east, and the Arakawa and the Tama still reach the bay on their own.' },
      { file: 'rivers_hokkaido', jp: '北海道', en: 'Hokkaido', note: 'The Ishikari drains the heart of the island from the Daisetsu mountains to the Sea of Japan. With the Shinano it carries more water than any other river in Japan, about 490 m³/s on average in this data. The phone wallpaper is framed on its basin.' },
    ],
    method: [
      ['Data', 'HydroRIVERS v1.0, from WWF and McGill University, traced from 15 arc-second (about 500 m) terrain: every river draining at least 10 km² or carrying at least 0.1 m³/s. Flows are modelled long-term averages, so they differ a little from gauged figures.'],
      ['Light', 'Each reach adds light along its length, more for more water (the square root of its flow), coloured from indigo to white on a log scale. Nothing is painted over, so confluences glow where the water gathers.'],
      ['Japan', 'Only reaches on Japan\'s islands in the Natural Earth 10 m land outlines are kept, the four islands of the Northern Territories among them, so no river from the continent, Sakhalin or Taiwan enters the frame. The national view is rotated so the islands run along the screen.'],
      ['Basins', 'Every reach records the outlet of its whole river system. Each system gets its own hue, the largest ones the most distinct.'],
      ['Animation', 'The rivers flow from their springs down to the sea, ordered by distance to the sea along the river: the far headwaters light first, every reach lights from its upstream end down, and all of them reach the coast together. The counter ends on the longest path from a spring to the sea in this data, the Tone\'s, 299.5 km. Official lengths, measured on finer maps, are longer: 322 km for the Tone and 367 km for the Shinano, Japan\'s longest river, which this data sends to the sea through the shorter Ōkōzu channel.'],
    ],
    sources: [
      ['HydroRIVERS v1.0, Lehner & Grill (2013), HydroSHEDS', 'https://www.hydrosheds.org/products/hydrorivers'],
      ['Natural Earth 10 m land', 'https://www.naturalearthdata.com/'],
    ],
  },
  {
    id: 'sakura',
    code: 'SK',
    kind: { jp: '季節', en: 'Season' },
    record: '5,843 blooms',
    scene: { file: 'sakura', title: 'The cherry blossom front', line: 'Sixty-six springs at 102 cities. The front leaves Okinawa in January and reaches Wakkanai in late May.' },
    still: 'sakura',
    short: 'Sakura',
    kanji: '桜',
    kana: 'さくら',
    title: 'Sakura front',
    accent: '#ff8fbf',
    anim: 'sakura',
    lede:
      'The first cherry blossom of the year at 102 cities, from 1953 to 2018. Each flower is one city in one year. The front sweeps from Okinawa in January to Wakkanai in late May. Older years are white, recent years pink, and pink tends to bloom first.',
    facts: [
      ['5,843', 'first-bloom dates'],
      ['102', 'cities'],
      ['~4 months', 'from Okinawa to Hokkaido'],
    ],
    scale: { label: 'Year', from: '1953', to: '2018', stops: ['#fff7fa', '#ff6ba8'] },
    wallpapers: [
      { file: 'sakura', jp: '桜前線', en: 'The sakura front', note: 'Left to right is the calendar, bottom to top is latitude. The isolated row in April at the bottom is a southern island station; Okinawa\'s January blooms are a different, early cherry.' },
      { file: 'sakura_map', jp: '桜の地図', en: 'Cherry blossom map', note: 'Every JMA observation city as a blossom. The deeper the pink, the earlier that city\'s first bloom now comes compared with the 1950s: 81 of 100 cities bloom earlier, the median city by about 5 days over 66 years. Pale blossoms have barely moved.' },
      { file: 'kyoto', jp: '京都の桜', en: 'Kyoto, 1,200 years', note: 'The longest flowering record on Earth: the day Kyoto\'s mountain cherries peaked, in 838 springs from 812 to today, read from old diaries and chronicles before modern observation. For a thousand years the bloom held near 15 April. Since 1900 it has slid earlier, and in 2023 it came on 25 March, the earliest on record. The deeper the pink, the earlier the year; the faint line is the 30-year average.' },
      { file: 'sakura_stripes', jp: '桜の縞', en: 'Sakura stripes', note: 'One thread of light per city, south at the bottom, 1953 on the left. A thread glows pink in the years that city bloomed early against its own average and dims to blue when it bloomed late. Warm springs light up the whole country at once as vertical bands, and after 1990 the pink takes over. Threads that stop around 2007 are stations where JMA ended the observation.' },
    ],
    method: [
      ['Data', 'JMA phenological observations: first-bloom date of the reference cherry tree at each station.'],
      ['Flowers', 'Each bloom is a five-petal sprite, randomly turned, blended additively so busy weeks glow.'],
      ['Stripes', 'For the 100 cities with 30+ years of records, each first-bloom date is compared with that city\'s own average. Nine days early or more is full pink, nine days late full blue; a missing year leaves a gap in the thread.'],
      ['Kyoto', 'Peak-bloom dates of Prunus jamasakura in Kyoto compiled by Yasuyuki Aono from historical documents, extended to the present. Pink measures how much earlier than the 812–1850 average (about 15 April) each year bloomed.'],
      ['Map', 'For each city with 30+ years of records, the trend of its first-bloom day is fitted with a Theil–Sen slope, which ignores odd years. Four station positions that were geocoded to towns abroad in the source file are corrected to their JMA sites.'],
    ],
    sources: [
      ['JMA さくらの開花日', 'https://www.data.jma.go.jp/sakura/data/index.html'],
      ['Dataset compiled by akg314/sakura', 'https://github.com/akg314/sakura'],
      ['Kyoto peak bloom since 812: Aono & Kazui (2008), Aono & Saito (2010), Katata (2026), via Our World in Data', 'https://ourworldindata.org/grapher/date-of-the-peak-cherry-tree-blossom-in-kyoto'],
    ],
  },
  {
    id: 'momiji',
    code: 'AL',
    kind: { jp: '季節', en: 'Season' },
    record: '4,391 maples',
    scene: { file: 'momiji', title: 'The autumn leaf front', line: 'The red runs south from Hokkaido in October to Kyushu in December, and it now comes about two weeks later than in the 1950s.' },
    still: 'momiji',
    short: 'Autumn',
    kanji: '紅葉',
    kana: 'こうよう',
    title: 'Autumn leaves',
    accent: '#ff4a5e',
    anim: 'momiji',
    lede:
      'The day the reference maple at each of 90 JMA stations first turned red, every autumn from 1953 to 2025. The front runs the opposite way to the cherry blossom, from Hokkaido in late October down to Kyushu in early December. Old autumns are gold and recent ones crimson, and the crimson trails behind: at the median city the leaves now turn about 16 days later than in the 1950s.',
    facts: [
      ['4,391', 'first red maples'],
      ['70 of 75', 'cities now turn later'],
      ['+3 days', 'per decade, median city'],
    ],
    scale: { label: 'Autumn', from: '1953', to: '2025', stops: ['#ffcc52', '#fa2933'] },
    wallpapers: [
      { file: 'momiji', jp: '紅葉前線', en: 'The autumn leaf front', note: 'Left to right is the calendar, bottom to top is latitude. Each maple leaf is one city in one autumn, gold for the 1950s, crimson for the last autumns. In almost every row the crimson leaves sit to the right of the gold: the red arrives later than it used to.' },
      { file: 'icho', jp: '銀杏の黄葉', en: 'Ginkgo gold', note: 'The same chart for the ginkgo trees JMA watches beside the maples: the day their leaves first turn yellow, at 82 cities. The ginkgo usually turns about five days before the maple, and it has drifted later too, by about 2.3 days per decade at the median city.' },
      { file: 'momiji_map', jp: '紅葉の地図', en: 'Autumn leaf map', note: 'Every JMA city with 30 or more autumns on record as a maple leaf. The deeper the red, the later its leaves now turn than in the 1950s: 70 of the 75 cities have shifted later, the median city by 3 days per decade. Pale leaves have barely moved.' },
      { file: 'momiji_stripes', jp: '紅葉の縞', en: 'Autumn leaf stripes', note: 'One thread of light per city, south at the bottom, 1953 on the left. A thread glows red in the autumns its maples turned late against its own average and dims to blue when they turned early. The red takes over after about 1990: the mirror of the sakura stripes, where warm springs glow pink.' },
    ],
    method: [
      ['Data', 'JMA phenological observations: the first day the reference maple at each station is judged to have turned red, and the first day its ginkgo turns yellow, 1953 to 2025. A few stations watch a substitute species; JMA counts those, and so do these pictures.'],
      ['Leaves', 'Each date is a leaf, blended additively so the busiest weeks glow. A date that slips into January stays with its autumn.'],
      ['Map', 'For each city with 30 or more autumns on record, the trend of its first red day is fitted with a Theil–Sen slope, which ignores odd years. Station positions are those of the sakura chapter, with the same four corrections.'],
      ['Stripes', 'For the 75 cities with 30 or more autumns, each date is compared with that city\'s own average. Twelve days late or more is full red, twelve days early full blue; a missing autumn leaves a gap in the thread.'],
      ['Animation', 'A date line sweeps from October into January, and a leaf lands at every city, all 73 autumns at once, as the line passes the day its maple turned red.'],
    ],
    sources: [
      ['JMA 生物季節観測累年値 (かえでの紅葉, いちょうの黄葉)', 'https://www.data.jma.go.jp/sakura/data/download_ruinenchi.html'],
    ],
  },
  {
    id: 'railways',
    code: 'RW',
    kind: { jp: '暮らし', en: 'Life' },
    record: '603 lines',
    scene: { file: 'trains_tokyo', title: 'Tokyo, every line in its own colour', line: 'The green Yamanote loop, the orange Chūō line cutting through it, the Shinkansen in white.' },
    still: 'trains_tokyo',
    short: 'Rail',
    kanji: '鉄道',
    kana: 'てつどう',
    title: 'Railways',
    accent: '#7dff9a',
    anim: 'trains',
    lede:
      'Every railway line in Japan in its official line colour, with the Shinkansen in white. Tokyo is the densest tangle on Earth: the green ring of the Yamanote line, the orange Chūō line cutting straight through it, and dozens of private lines fanning out to the suburbs.',
    facts: [
      ['603', 'lines in service'],
      ['8,989', 'stations'],
      ['1964', 'first Shinkansen'],
    ],
    scale: { label: 'Official line colours', from: 'JR', to: 'Shinkansen', stops: ['#00b261', '#ff8c00', '#e6334d', '#1a80e6', '#ffffff'] },
    wallpapers: [
      { file: 'trains_tokyo', jp: '東京', en: 'Tokyo', note: 'The Yamanote loop with every line that crosses it. The white lines are the Tōhoku, Jōetsu and Tōkaidō Shinkansen meeting at Tokyo Station.' },
      { file: 'trains_kansai', jp: '関西', en: 'Osaka, Kyoto & Kobe', note: 'Three cities joined by competing parallel lines: JR, Hankyu, Hanshin and Keihan all race between Osaka, Kyoto and Kobe.' },
      { file: 'trains_japan', jp: '日本', en: 'Japan', note: 'The whole network, rotated so the islands run along the screen. The Shinkansen is the white spine from Kagoshima to Hokkaido.' },
    ],
    method: [
      ['Data', 'National Land Numerical Information (国土数値情報) railway data, via the jprailway package: track geometry, official line colours, stations.'],
      ['Colour', 'Each line keeps its official colour, slightly lifted so dark colours still glow. Lines without one are a dim warm white. Closed lines are left out.'],
    ],
    sources: [
      ['国土数値情報 鉄道データ (MLIT)', 'https://nlftp.mlit.go.jp/ksj/'],
      ['jprailway (paithiov909)', 'https://github.com/paithiov909/jprailway'],
    ],
  },
  {
    id: 'night',
    code: 'NT',
    kind: { jp: '暮らし', en: 'Life' },
    record: 'Night of 2016',
    scene: { file: 'night_japan', title: 'Japan at night, from space', line: 'The real light of the cities, as a satellite saw it. The Tōkaidō burns from Tokyo to Osaka; four-fifths of the land stays dark.' },
    still: 'night_japan',
    short: 'Night',
    kanji: '夜',
    kana: 'よる',
    title: 'Japan at night',
    accent: '#b9a3ff',
    anim: 'night',
    lede:
      'The only chapter that is light already: Japan as NASA\'s Suomi NPP satellite saw it on the clearest nights of 2016. The Tōkaidō corridor burns almost unbroken from Tokyo to Osaka, and a box around Kantō holds a third of all the light on a tenth of the land. Around four-fifths of the islands stays dark: the mountains, where the rivers begin.',
    facts: [
      ['500 m', 'per pixel'],
      ['32%', 'of the light in Kantō'],
      ['81%', 'of the land dark'],
    ],
    scale: { label: 'Light', from: 'dim towns', to: 'city cores', stops: ['#ff8c33', '#ffbd6b', '#ffe6b8', '#ffffff'] },
    wallpapers: [
      { file: 'night_japan', jp: '夜の日本', en: 'Japan at night', note: 'Every light on Japan\'s islands in 2016, the same rotated frame as the Rivers chapter, warm amber where the light is faint and white where it is brightest. The lights of Korea, China and Russia are switched off at the coast, so the islands float alone.' },
      { file: 'night_tokaido', jp: '東海道', en: 'The Tōkaidō corridor', note: 'Tokyo, Nagoya and Osaka, and the almost unbroken string of cities between them along the old Tōkaidō road, where the Shinkansen runs today. Tokyo Bay is the dark notch in the brightest light. The phone wallpaper holds Kantō alone.' },
      { file: 'night_rivers', jp: '光と川', en: 'Light and rivers', note: 'The lights over the faint river network of the Rivers chapter. The cities crowd onto the plains where the rivers meet the sea; upstream, the valleys stay dark all the way to the springs.' },
    ],
    method: [
      ['Data', 'NASA Earth Observatory Black Marble 2016: a composite of the best cloud-free nights of each month of the year from the VIIRS day/night band on the Suomi NPP satellite, at 15 arc-seconds (about 500 m). This grayscale image is NASA\'s visual stretch of the light, not a calibrated measurement, so the shares on this page are measured in the image.'],
      ['Japan', 'Only light on Japan\'s islands, the land of the Rivers chapter grown by about 4 km for the coast and its harbours, is kept. The rest of the picture is pixels switched off.'],
      ['Light', 'The stretch is eased back towards linear light so the city cores keep their streets, then coloured from amber for the faintest glow to white for the brightest.'],
      ['Animation', 'Nightfall on the autumn equinox, 23 September 2025: each pixel comes on over about 20 minutes after its own sunset, computed from NOAA\'s solar equations. The sun sets first on Iturup, around 17:05 JST, then on eastern Hokkaido around 17:15, and last on the Ryukyus, after 18:40; Tokyo goes dark at 17:38.'],
    ],
    sources: [
      ['NASA Earth Observatory, Black Marble 2016 (Suomi NPP VIIRS)', 'https://science.nasa.gov/earth/earth-observatory/earth-at-night/maps/'],
      ['NOAA Global Monitoring Laboratory, General solar position calculations', 'https://gml.noaa.gov/grad/solcalc/solareqns.PDF'],
    ],
  },
]
